### ISSUE TITLE
Improving 3AC code generation

### ISSUE THREAD

**Issue by OO-ps** [OO-ps/oogway#2]
@sharadhotha @sarathisalwaysbusy Please comment the inputs and outputs you check in comments on this issue. Also, where ever applicable also mention the problems with the 3AC code generated. 

### NOTE
Arguments 3AC, hasn't been taken care of yet. We can look it into it later.

**Comment by sharadhotha** [comment]
### Comment Type: Problem (doesn't show error when it has to)
Input:
```
main(){
	a=5;
	b=6;
	n=h(());;
}
```
Output
```
def main:
MOV t0 5
MOV t1 6
CALL h
MOV t3 ret_loc
MOV t2 t3
```

**Comment by sharadhotha** [comment]
### Comment Type: Problem (shows error when it need not)
Input:
```
main(){
	a=5;
	b=6;
	n=h();
}
```
Output:
```
line 4:4 missing '(' at ')'
line 4:5 missing ')' at ';'
line 5:0 missing ';' at '}'
def main:
MOV t0 5
MOV t1 6
CALL h
MOV t3 ret_loc
MOV t2 t3
```

**Comment by sharadhotha** [comment]
### Comment Type: Problem (IF Statement Doesn't Execute)
Input
```
main(){
	if(a>6){
		a=5;
	}
}
```
Output:
```
Exception in thread "main" java.lang.NullPointerException
        at bphc.cse.dragon.OogwayParser.stat(OogwayParser.java:452)
        at bphc.cse.dragon.OogwayParser.body(OogwayParser.java:351)
        at bphc.cse.dragon.OogwayParser.main_func(OogwayParser.java:302)
        at bphc.cse.dragon.OogwayParser.start(OogwayParser.java:181)
        at bphc.cse.dragon.TAC.main(TAC.java:21)
```

**Comment by sharadhotha** [comment]
### Comment Type: Success (While Loops and Nested While Loops Work)
Input:
```
main(){
	while(a>6){
		a=5;
		while(b<5){
			b=6;
		}
	}

}
```
Output:
```
def main:
GT t1 t0 6
JMPEVAL t1 t5
MOV t0 5
LT t3 t2 5
JMPEVAL t3 t4
MOV t2 6
t4
t5
```

**Comment by OO-ps** [comment]
@sharadhotha
The first two problems are related, right ! I updated the grammar, here's my output ! let me know if this is correct: 

```
def main:
MOV t0 5
MOV t1 6
CALL h
MOV t3 ret_loc
MOV t2 t3
```

**Comment by OO-ps** [comment]
@sharadhotha loops jump locations should have `colons` following them ! I will update for that too.

**Comment by OO-ps** [comment]
@sharadhotha 
Here's my correction for `if-else` issue. Please let me know if the solution is correct 

_(I am not going through the solution 3AC in a detailed fashion. Please be thorough as you go through them)_

```
def main:
GT t1 t0 6
JMPEVAL t1 t2
MOV t0 5
t2:
```

**Comment by sharadhotha** [comment]
@OO-ps
Yeap. The output is as expected: in both ```func_call``` and ```if-else```.
I checked other possibilities as well. And the output is correct. Posting it below.

**Comment by sharadhotha** [comment]
### Comment Type: Problem (output doesn't call syscall)
Input:
```
main(){
	a=5;
	b="India";
	input c
	output "string"
	d=a+c*4/6+6+8.885+h(());;
	while(5+8*8==5+9)
	{
		g=8.8;
	}	
}
```
Output:
```
def main:
MOV t0 5
MOV t1 "India"
Syscall read t2
null
MUL t4 t2 4
DIV t5 t4 6
ADD t6 t0 t5
ADD t7 t6 6
ADD t8 t7 8.885
CALL h
MOV t9 ret_loc
ADD t10 t8 t9
MOV t3 t10
MUL t11 8 8
ADD t12 5 t11
ADD t13 5 9
EQ t14 t12 t13
JMPEVAL t14 t16
MOV t15 8.8
t16
```

**Comment by OO-ps** [comment]
@sharadhotha  the above case hints at some other problesm. change **success** to **problems** in you comment.

Also, please check with say 3 arithmetic op lines in two loops, one nested within the  other and say if logic persists. Thanks.

**Comment by OO-ps** [comment]
@sharadhotha The output issue has been sorted. Look at the following inputs and outputs:

**INPUT:**
```
main(){
    output "yo"
}

```

**OUTPUT:**
```
main(){
    output "yo"
}

```
